DROP SCHEMA IF EXISTS ot CASCADE;
DROP SCHEMA IF EXISTS companies CASCADE;
DROP SCHEMA IF EXISTS files CASCADE;
DROP SCHEMA IF EXISTS catalogs CASCADE;
DROP TABLE IF EXISTS identity.support_tickets CASCADE;
DROP TABLE IF EXISTS identity.login_attempts CASCADE;
DROP TABLE IF EXISTS identity.password_policies CASCADE;
DROP TABLE IF EXISTS identity.refresh_tokens CASCADE;
DROP TABLE IF EXISTS identity.password_reset_tokens CASCADE;
DROP TABLE IF EXISTS identity.onboarding_invitations CASCADE;
DROP TABLE IF EXISTS identity.user_roles CASCADE;
DROP TABLE IF EXISTS identity.role_permissions CASCADE;
DROP TABLE IF EXISTS identity.roles CASCADE;
DROP TABLE IF EXISTS identity.permissions CASCADE;
DROP TABLE IF EXISTS identity.profiles CASCADE;
DROP TABLE IF EXISTS identity.users CASCADE;
DROP TABLE IF EXISTS identity.tenants CASCADE;
DROP FUNCTION IF EXISTS identity.find_user_for_auth(citext);
DROP FUNCTION IF EXISTS identity.is_super_admin();
