<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <RootNamespace>Flit.Modules.Procedures</RootNamespace>
    <PublishAot>false</PublishAot>
    <IsAotCompatible>false</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Flit.SharedKernel\Flit.SharedKernel.csproj" />
    <ProjectReference Include="..\Flit.Modules.ProceduresConfig\Flit.Modules.ProceduresConfig.csproj" />
    <ProjectReference Include="..\Flit.Modules.Integrations\Flit.Modules.Integrations.csproj" />
  </ItemGroup>
</Project>
